services:
  midi-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-midi-server
    devices:
      - '/dev/snd:/dev/snd'
    group_add:
      - audio
    ports:
      - '3010:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
